import course
import song

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='ERWC',
                  teacher_name='Ms. Wenzell',
                  resource_name='ArtHistory.net',
                  resource_url='http://www.arthistory.net/'),
    course.Course(period=3,
                  name='TA',
                  teacher_name='Ms. Lee',
                  resource_name='N/A',
                  resource_url='N/A'),
    course.Course(period=4,
                  name='Statistics',
                  teacher_name='Ms. Chand',
                  resource_name='Interactive simulations',
                  resource_url='https://www.khanacademy.org/math/statistics-probability'),
    course.Course(period=5,
                  name='Economics',
                  teacher_name='Mr. Seelbach',
                  resource_name='Investopedia',
                  resource_url='https://www.investopedia.com/university/all/economics/'),
    course.Course(period=6,
                  name='Free',
                  teacher_name='N/A',
                  resource_name='N/A',
                  resource_url='N/A')
]

TOP_TEN_SONGS = [
    song.Song(title="KIRBY MUSIC",
              artist_name="Jun Ishikawa",
              youtube_url="https://www.youtube.com/embed/E1AcM1u9Xkk"),
    song.Song(title="Cliffs of Dover",
              artist_name="Eric Johnson",
              youtube_url="https://www.youtube.com/embed/sCdYk7F72dI"),
    song.Song(title="Knights of Cyndonia",
              artist_name="Muse",
              youtube_url="https://www.youtube.com/embed/z9D71pQaTnc"),
    song.Song(title="Tattoos",
              artist_name="Caravan Palace",
              youtube_url="https://www.youtube.com/embed/qQ-Pyx4joKM"),
    song.Song(title="Doing It For The Money",
              artist_name="Foster The People",
              youtube_url="https://www.youtube.com/embed/dJ1VorN9Cl0"),
    song.Song(title="A Beginner's Guide to Destroying the Moon",
              artist_name="Foster the People",
              youtube_url="https://www.youtube.com/embed/Gt-sW6H2UMM"),
    song.Song(title="Face To Face",
              artist_name="Daft Punk",
              youtube_url="https://www.youtube.com/embed/zNRbP7U0Iq8"),
    song.Song(title="Underlying Problem",
              artist_name="	Jake Kaufman and Manami Matsumae",
              youtube_url="https://www.youtube.com/embed/dWg3KmaIhRU"),
    song.Song(title="My Name is Jonas",
              artist_name="Weezer",
              youtube_url="https://www.youtube.com/embed/VoAnLHSLHGQ"),
    song.Song(title="The Apprentice",
              artist_name="Gorillaz",
              youtube_url="https://www.youtube.com/embed/LdPyYze2NIA"),
]