import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='ERWC',
                  teacher_name='Ms. Wenzell',
                  resource_name='ArtHistory.net',
                  resource_url='http://www.arthistory.net/'),
    course.Course(period=3,
                  name='TA',
                  teacher_name='Ms. Lee',
                  resource_name='N/A',
                  resource_url='N/A'),
    course.Course(period=4,
                  name='Statistics',
                  teacher_name='Ms. Chand',
                  resource_name='Interactive simulations',
                  resource_url='https://www.khanacademy.org/math/statistics-probability'),
    course.Course(period=5,
                  name='Economics',
                  teacher_name='Mr. Seelbach',
                  resource_name='Investopedia',
                  resource_url='https://www.investopedia.com/university/all/economics/'),
    course.Course(period=6,
                  name='Free',
                  teacher_name='N/A',
                  resource_name='N/A',
                  resource_url='N/A'),
]
