import song


TOP_TEN_SONGS = [
    song.Song(title="KIRBY MUSIC",
              artist_name="Jun Ishikawa",
              youtube_url="https://www.youtube.com/embed/E1AcM1u9Xkk"),
    song.Song(title="Cliffs of Dover",
              artist_name="Eric Johnson",
              youtube_url="https://www.youtube.com/embed/sCdYk7F72dI"),
    song.Song(title="Knights of Cyndonia",
              artist_name="Muse",
              youtube_url="https://www.youtube.com/embed/z9D71pQaTnc"),
    song.Song(title="Tattoos",
              artist_name="Caravan Palace",
              youtube_url="https://www.youtube.com/embed/qQ-Pyx4joKM"),
    song.Song(title="Doing It For The Money",
              artist_name="Foster The People",
              youtube_url="https://www.youtube.com/embed/dJ1VorN9Cl0"),
    song.Song(title="A Beginner's Guide to Destroying the Moon",
              artist_name="Foster the People",
              youtube_url="https://www.youtube.com/embed/Gt-sW6H2UMM"),
    song.Song(title="Face To Face",
              artist_name="Daft Punk",
              youtube_url="https://www.youtube.com/embed/zNRbP7U0Iq8"),
    song.Song(title="Underlying Problem",
              artist_name="	Jake Kaufman and Manami Matsumae",
              youtube_url="https://www.youtube.com/embed/dWg3KmaIhRU"),
    song.Song(title="My Name is Jonas",
              artist_name="Weezer",
              youtube_url="https://www.youtube.com/embed/VoAnLHSLHGQ"),
    song.Song(title="The Apprentice",
              artist_name="Gorillaz",
              youtube_url="https://www.youtube.com/embed/LdPyYze2NIA"),
]